In [1]:
import scipy.special
import numpy as np
import matplotlib.pyplot
from sklearn.datasets import fetch_openml
%matplotlib inline

In [2]:
mnist = fetch_openml('mnist_784')

In [35]:
mnist.data.shape, mnist.target.shape

((70000, 784), (70000,))

In [36]:
data = mnist.data
target = mnist.target

In [37]:
np.shape(data)

(70000, 784)

In [38]:
target1 = target.astype(str).astype(int)

In [39]:
target1

array([5, 0, 4, ..., 4, 5, 6])

In [40]:
def onehot(labels,classes):
    y = np.eye(classes)
    return y[labels]


target2 = onehot(target1,10)

In [41]:
target2

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [42]:
x = data[:30000] 

In [43]:
y = target2[:30000]

In [44]:
XT = x.T

In [45]:
R1 = np.random.randn(30000,500)

In [46]:
W1 = XT@R1
np.shape(W1)

(784, 500)

In [47]:
O1 = x@W1
O1

array([[ 3.81158535e+08, -2.09067075e+08, -2.87601298e+08, ...,
        -1.35822050e+07, -9.58647645e+06,  4.52946898e+08],
       [ 4.51250279e+08, -2.64911576e+08, -2.26997012e+08, ...,
         7.75252849e+07,  2.11196553e+08,  4.84022774e+08],
       [ 1.58123588e+08, -1.78537506e+08, -3.16723083e+08, ...,
         3.60593712e+07, -5.30506987e+07,  2.50657413e+08],
       ...,
       [ 2.89983833e+08, -2.44285531e+08, -2.97911279e+08, ...,
         1.11897344e+08, -1.20021605e+08,  4.59570583e+08],
       [ 1.26990270e+08, -1.62854685e+08, -2.72866265e+08, ...,
         1.61918135e+07, -1.43051566e+08,  1.61770173e+08],
       [ 2.92218182e+08, -2.52789997e+07, -2.18298275e+08, ...,
        -8.49927072e+07, -1.11502283e+08,  2.66644920e+08]])

In [48]:
FO1 = np.arctan(O1)
FO1

array([[ 1.57079632, -1.57079632, -1.57079632, ..., -1.57079625,
        -1.57079622,  1.57079632],
       [ 1.57079632, -1.57079632, -1.57079632, ...,  1.57079631,
         1.57079632,  1.57079632],
       [ 1.57079632, -1.57079632, -1.57079632, ...,  1.5707963 ,
        -1.57079631,  1.57079632],
       ...,
       [ 1.57079632, -1.57079632, -1.57079632, ...,  1.57079632,
        -1.57079632,  1.57079632],
       [ 1.57079632, -1.57079632, -1.57079632, ...,  1.57079627,
        -1.57079632,  1.57079632],
       [ 1.57079632, -1.57079629, -1.57079632, ..., -1.57079632,
        -1.57079632,  1.57079632]])

In [49]:
aa = np.linalg.pinv(FO1)

In [50]:
w2 = aa@y

In [51]:


aaa = np.linalg.pinv(w2)

np.shape(aaa)

(10, 500)

In [52]:
NEWW1 = np.linalg.pinv(x)@(np.tan(y@aaa))

In [53]:
NEWW2 = (np.linalg.pinv(np.arctan(x@NEWW1)))@y

In [54]:
plz = (np.arctan(x@NEWW1))@NEWW2

In [55]:
np.argmax(plz,axis =1)

array([5, 0, 4, ..., 6, 7, 1], dtype=int64)

In [56]:
target1[:30000]

array([5, 0, 4, ..., 6, 7, 1])

In [57]:
xtest = data[35000:40000] 

In [58]:
len(xtest)

5000

In [59]:
a = np.arctan(xtest@NEWW1)

In [60]:
plz2 = a@NEWW2

In [61]:
plz2[0]

array([-0.0420723 ,  0.95944214,  0.02406311,  0.02118683,  0.0294342 ,
        0.05804443,  0.01046753, -0.05569458, -0.03326416,  0.02822876])

In [62]:
predict = np.argmax(plz2,axis =1)
predict = predict.tolist()
predict

[1,
 1,
 9,
 4,
 9,
 8,
 1,
 8,
 1,
 1,
 3,
 2,
 0,
 9,
 2,
 3,
 7,
 8,
 5,
 9,
 2,
 8,
 1,
 2,
 9,
 8,
 5,
 6,
 0,
 5,
 3,
 2,
 7,
 6,
 5,
 2,
 8,
 6,
 8,
 0,
 5,
 5,
 5,
 3,
 8,
 3,
 5,
 6,
 1,
 3,
 0,
 2,
 1,
 7,
 9,
 6,
 0,
 5,
 3,
 9,
 0,
 8,
 5,
 0,
 6,
 9,
 3,
 0,
 4,
 1,
 9,
 2,
 8,
 3,
 0,
 4,
 2,
 5,
 4,
 6,
 7,
 7,
 5,
 8,
 9,
 9,
 3,
 0,
 5,
 1,
 8,
 2,
 2,
 3,
 1,
 4,
 8,
 5,
 4,
 6,
 5,
 7,
 9,
 8,
 2,
 9,
 2,
 0,
 1,
 1,
 2,
 2,
 2,
 3,
 9,
 4,
 1,
 5,
 9,
 6,
 8,
 7,
 3,
 5,
 1,
 9,
 4,
 9,
 0,
 8,
 7,
 6,
 3,
 5,
 2,
 9,
 9,
 2,
 7,
 3,
 6,
 4,
 4,
 3,
 4,
 8,
 6,
 5,
 0,
 1,
 7,
 5,
 4,
 2,
 6,
 3,
 3,
 5,
 6,
 1,
 7,
 2,
 3,
 1,
 5,
 3,
 9,
 2,
 1,
 6,
 3,
 5,
 5,
 3,
 9,
 0,
 7,
 7,
 4,
 4,
 7,
 6,
 9,
 4,
 6,
 0,
 4,
 5,
 9,
 4,
 3,
 9,
 0,
 5,
 9,
 3,
 3,
 1,
 0,
 7,
 6,
 4,
 2,
 7,
 6,
 1,
 6,
 5,
 3,
 0,
 6,
 6,
 1,
 6,
 5,
 2,
 2,
 0,
 7,
 6,
 2,
 3,
 6,
 7,
 3,
 4,
 5,
 4,
 5,
 4,
 8,
 3,
 4,
 7,
 6,
 2,
 2,
 8,
 6,
 9,
 2,
 6,
 8,
 0,
 1,
 9,
 8,
 5,
 5,
 3,


In [63]:
testy = target1[35000:40000]
testy = testy.tolist()

In [64]:
testy

[1,
 1,
 9,
 4,
 9,
 8,
 1,
 8,
 1,
 1,
 3,
 2,
 0,
 9,
 2,
 3,
 9,
 8,
 8,
 9,
 2,
 8,
 3,
 2,
 9,
 8,
 6,
 6,
 0,
 5,
 3,
 2,
 7,
 6,
 6,
 2,
 8,
 6,
 8,
 0,
 5,
 5,
 8,
 3,
 8,
 3,
 5,
 6,
 1,
 3,
 0,
 2,
 1,
 7,
 9,
 6,
 0,
 5,
 3,
 9,
 0,
 8,
 5,
 0,
 0,
 9,
 3,
 0,
 9,
 1,
 9,
 2,
 8,
 3,
 0,
 4,
 2,
 5,
 4,
 6,
 9,
 7,
 5,
 8,
 9,
 9,
 3,
 0,
 8,
 1,
 2,
 2,
 2,
 3,
 1,
 4,
 8,
 5,
 4,
 6,
 5,
 7,
 7,
 8,
 2,
 9,
 2,
 0,
 1,
 1,
 2,
 2,
 2,
 3,
 5,
 4,
 1,
 5,
 9,
 6,
 8,
 7,
 3,
 8,
 2,
 9,
 4,
 9,
 2,
 8,
 7,
 6,
 3,
 5,
 2,
 9,
 4,
 2,
 2,
 3,
 6,
 4,
 4,
 3,
 4,
 8,
 6,
 5,
 0,
 1,
 7,
 5,
 4,
 2,
 6,
 3,
 3,
 0,
 6,
 1,
 9,
 2,
 3,
 1,
 5,
 3,
 4,
 2,
 1,
 6,
 3,
 5,
 5,
 3,
 9,
 0,
 7,
 7,
 4,
 4,
 3,
 6,
 9,
 4,
 6,
 0,
 4,
 5,
 9,
 9,
 3,
 9,
 0,
 8,
 9,
 3,
 7,
 1,
 2,
 7,
 6,
 4,
 2,
 7,
 6,
 6,
 6,
 5,
 3,
 0,
 6,
 6,
 1,
 6,
 5,
 2,
 2,
 0,
 9,
 6,
 2,
 3,
 6,
 7,
 5,
 7,
 3,
 4,
 5,
 4,
 8,
 3,
 8,
 9,
 4,
 2,
 1,
 8,
 6,
 9,
 2,
 6,
 8,
 0,
 1,
 9,
 8,
 5,
 3,
 3,


In [65]:
scorecard = []

for i in range(len(xtest)):
    correct_label = testy[i]
    label = predict[i]
    print(label)
    if(label == correct_label):
        scorecard.append(1)
    else:
        scorecard.append(0)
        pass
    pass

1
1
9
4
9
8
1
8
1
1
3
2
0
9
2
3
7
8
5
9
2
8
1
2
9
8
5
6
0
5
3
2
7
6
5
2
8
6
8
0
5
5
5
3
8
3
5
6
1
3
0
2
1
7
9
6
0
5
3
9
0
8
5
0
6
9
3
0
4
1
9
2
8
3
0
4
2
5
4
6
7
7
5
8
9
9
3
0
5
1
8
2
2
3
1
4
8
5
4
6
5
7
9
8
2
9
2
0
1
1
2
2
2
3
9
4
1
5
9
6
8
7
3
5
1
9
4
9
0
8
7
6
3
5
2
9
9
2
7
3
6
4
4
3
4
8
6
5
0
1
7
5
4
2
6
3
3
5
6
1
7
2
3
1
5
3
9
2
1
6
3
5
5
3
9
0
7
7
4
4
7
6
9
4
6
0
4
5
9
4
3
9
0
5
9
3
3
1
0
7
6
4
2
7
6
1
6
5
3
0
6
6
1
6
5
2
2
0
7
6
2
3
6
7
3
4
5
4
5
4
8
3
4
7
6
2
2
8
6
9
2
6
8
0
1
9
8
5
5
3
2
8
1
8
4
7
4
1
4
4
7
0
0
4
8
8
1
5
5
2
1
3
5
9
5
0
5
7
1
2
6
1
0
7
6
1
1
5
2
1
2
7
9
4
0
8
9
6
2
1
8
2
0
1
4
6
7
8
8
8
8
0
4
1
4
2
4
3
6
4
0
7
6
8
4
9
0
0
1
1
9
2
7
3
7
4
3
7
8
8
2
9
0
0
1
1
3
2
0
3
5
7
1
8
3
9
2
1
9
1
8
7
4
4
8
8
3
1
9
5
1
9
7
2
9
8
3
6
6
3
9
9
9
8
9
6
1
9
5
1
5
7
4
2
5
1
1
1
8
1
0
2
4
2
1
2
5
3
0
0
2
6
4
4
1
3
7
7
4
6
9
9
3
0
0
9
6
1
1
4
1
0
0
6
3
1
1
2
8
6
9
7
4
2
9
2
7
3
1
0
9
7
6
2
2
9
2
2
3
3
8
4
5
0
3
0
5
8
6
7
8
8
4
0
7
4
7
8
2
9
1
0
2
2
8
0
3
1
0
6
4
3
2
4
2
5
1
6
8
7


5
5
8
9
6
9
7
7
0
6
6
4
8
7
2
9
6
7
3
2
9
1
3
1
2
4
8
0
6
5
1
3
7
0
4
8
8
6
8
0
9
9
0
7
3
3
3
0
9
1
0
0
5
6
2
0
5
2
6
6
9
4
4
4
1
4
8
9
3
9
7
2
5
1
1
9
7
6
7
1
8
9
2
4
9
8
7
9
8
6
6
0
6
5
4
2
2
4
5
7
2
4
3
7
6
3
6
4
5
2
6
1
0
3
7
6
5
4
2
9
8
9
1
3
6
2
1
5
0
9
4
3
8
3
1
1
6
0
1
7
8
0
0
1
1
9
2
4
3
5
4
9
5
2
6
3
7
4
9
4
9
8
0
6
1
4
2
0
2
6
4
3
0
0
6
5
7
2
1
7
7
9
0
8
1
0
2
7
3
9
4
8
0
6
6
9
9
3
0
2
4
3
0
8
6
0
1
5
7
1
4
7
1
3
9
0
0
2
4
6
5
2
4
1
1
3
4
0
0
9
5
5
1
4
5
5
4
0
0
4
7
3
6
4
0
6
1
1
7
1
0
6
6
7
5
1
9
4
5
5
4
9
7
3
6
1
0
2
1
9
1
4
7
1
7
0
1
0
3
3
2
0
3
0
1
5
0
2
0
2
7
8
1
4
4
7
7
6
3
8
1
0
4
8
4
1
4
7
5
8
6
3
3
4
6
1
7
0
4
2
6
4
9
1
0
0
4
3
5
8
5
3
1
0
3
6
3
5
7
1
9
2
5
4
7
2
2
7
4
8
5
9
7
8
7
5
2
2
1
9
3
6
0
1
1
1
2
5
3
0
6
0
3
5
6
8
7
1
5
0
9
4
0
0
1
5
2
0
3
5
4
5
5
5
6
0
7
2
8
5
9
9
0
4
1
3
2
1
3
3
4
1
5
1
6
1
7
4
8
0
9
9
8
5
9
9
6


In [66]:
scorecard_array = np.asarray(scorecard)
print("performance = ", scorecard_array.sum() / scorecard_array.size)

performance =  0.8482
